export const players = [
  "Draymond Green",
  "Giannis Antetokounmpo",
  "Russell Westbrook",
  "Avery Bradley",
  "Ja Morant",
  "Jayson Tatum",
  "Jaylen Brown",
  "Wesley Matthews",
  "Steven Adams",
  "Brandon Ingram",
  "Lonzo Ball",
  "Stephen Curry",
  "Kobe Bryant",
  "James Harden",
  "Joel Embiid",
  "Kyrie Irving",
  "Anthony Davis",
  "Carmelo Anthony",
  "Chris Paul",
  "Devin Harris",
  "J.J. Redick",
  "Kevin Love",
  "Richard Jefferson"
];
